from io import BytesIO

from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer
)


def generate_pdf_report(
    patient_name,
    patient_age,
    patient_gender,
    image_name,
    prediction,
    confidence,
    date,
    time,
    report_type="Medical Image"
):

    buffer = BytesIO()

    doc = SimpleDocTemplate(buffer)

    styles = getSampleStyleSheet()

    elements = []

    # --------------------------------------------------
    # Title
    # --------------------------------------------------

    elements.append(
        Paragraph(
            "<b><font size='22'>DiagNova</font></b>",
            styles["Title"]
        )
    )

    elements.append(
        Paragraph(
            f"AI-Powered {report_type} Analysis Report",
            styles["Heading2"]
        )
    )

    elements.append(Spacer(1, 20))

    # --------------------------------------------------
    # Patient Information
    # --------------------------------------------------

    elements.append(
        Paragraph(
            "<b>Patient Information</b>",
            styles["Heading3"]
        )
    )

    elements.append(
        Paragraph(
            f"<b>Name:</b> {patient_name}",
            styles["Normal"]
        )
    )

    elements.append(
        Paragraph(
            f"<b>Age:</b> {patient_age}",
            styles["Normal"]
        )
    )

    elements.append(
        Paragraph(
            f"<b>Gender:</b> {patient_gender}",
            styles["Normal"]
        )
    )

    elements.append(Spacer(1, 15))

    # --------------------------------------------------
    # Prediction Details
    # --------------------------------------------------

    elements.append(
        Paragraph(
            f"<b>{report_type} Prediction Details</b>",
            styles["Heading3"]
        )
    )

    elements.append(
        Paragraph(
            f"<b>Image Name:</b> {image_name}",
            styles["Normal"]
        )
    )

    elements.append(
        Paragraph(
            f"<b>Prediction:</b> {prediction.upper()}",
            styles["Normal"]
        )
    )

    elements.append(
        Paragraph(
            f"<b>Confidence:</b> {confidence:.2f}%",
            styles["Normal"]
        )
    )

    elements.append(
        Paragraph(
            f"<b>Date:</b> {date}",
            styles["Normal"]
        )
    )

    elements.append(
        Paragraph(
            f"<b>Time:</b> {time}",
            styles["Normal"]
        )
    )

    elements.append(Spacer(1, 20))

    # --------------------------------------------------
    # Disclaimer
    # --------------------------------------------------

    elements.append(
        Paragraph(
            "<b>Disclaimer</b>",
            styles["Heading3"]
        )
    )

    elements.append(
        Paragraph(
            "This report is generated by the DiagNova AI model "
            "for educational and research purposes only. "
            "It should not be considered a medical diagnosis. "
            "Please consult a qualified healthcare professional.",
            styles["BodyText"]
        )
    )

    elements.append(Spacer(1, 25))

    # --------------------------------------------------
    # Footer
    # --------------------------------------------------

    elements.append(
        Paragraph(
            "DiagNova • AI Medical Image Analysis",
            styles["Italic"]
        )
    )

    # Build PDF
    doc.build(elements)

    pdf = buffer.getvalue()

    buffer.close()

    return pdf