import os
import streamlit as st

from components.sidebar import show_sidebar
from components.patient_form import patient_information
from components.upload import upload_image
from components.prediction import prediction_section
from components.history import show_history


# Page Configuration
st.set_page_config(
    page_title="DiagNova",
    page_icon="🩺",
    layout="wide"
)


# Session State
if "history" not in st.session_state:
    st.session_state.history = []


# Sidebar
show_sidebar()


# Logo & Header
logo_path = os.path.join(
    os.path.dirname(__file__),
    "assets",
    "logo.png"
)

col1, col2 = st.columns([1, 5])

with col1:
    st.image(
        logo_path,
        width=110
    )

with col2:
    st.markdown(
        """
        <h1 style="
        color:#2563EB;
        margin-bottom:5px;
        ">
        👋 Welcome to DiagNova
        </h1>

        <h3 style="
        color:#3B82F6;
        margin-top:0px;
        margin-bottom:8px;
        ">
        AI-Powered Medical Image Analysis Platform
        </h3>
        """,
        unsafe_allow_html=True
    )

    st.caption(
        "Medical Image Intelligence • Deep Learning • Computer Vision"
    )

st.divider()


# Patient Information
patient_name, patient_age, patient_gender = patient_information()


# Upload Section
uploaded_file, image, right = upload_image()


# Prediction Section
if uploaded_file is not None:
    with right:
        prediction_section(
            uploaded_file,
            patient_name,
            patient_age,
            patient_gender
        )


# History
show_history()


# Project Highlights
st.subheader("🚀 Project Highlights")

col1, col2, col3 = st.columns(3)

with col1:
    st.info(
        """
### 🧠 AI Model

• Custom CNN

• Binary Classification

• Chest X-ray Analysis
"""
    )

with col2:
    st.info(
        """
### 💻 Technologies

• Python

• PyTorch

• Streamlit
"""
    )

with col3:
    st.info(
        """
### ⭐ Features

• Real-time Prediction

• Confidence Score

• Interactive UI
"""
    )

st.divider()


# About DiagNova
st.subheader("ℹ️ About DiagNova")

st.write(
    """
DiagNova is an AI-powered medical image analysis platform that assists in the early detection of pneumonia from Chest X-ray images using Deep Learning.

The project demonstrates the complete AI workflow including image preprocessing, CNN model training, evaluation, real-time prediction, and deployment through Streamlit.

Its modular architecture also allows future expansion into multiple medical imaging applications.
"""
)

st.divider()


# Disclaimer
st.warning(
    """
**Disclaimer**

DiagNova is developed for educational and research purposes only.

The predictions generated by this application are AI-assisted results and should not be considered a substitute for professional medical diagnosis.

Always consult a qualified healthcare professional before making clinical decisions.
"""
)

st.divider()


# Footer
st.markdown(
    """
<div style="text-align:center;color:#64748B;">
© 2026 DiagNova | AI Medical Image Analysis Platform
</div>
""",
    unsafe_allow_html=True
)